[server]
headless = true
enableCORS = false

[theme]
primaryColor = "#0099FF"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#222222"
font = "sans serif"

[ui]
language = "ja" 